# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experiment2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='experiment2.proto',
  package='Experiment2Data',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x65xperiment2.proto\x12\x0f\x45xperiment2Data\"\xaa\x01\n\x10\x45xperiment2_prop\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x10\n\x08latitude\x18\x02 \x02(\x02\x12\x11\n\tlongitude\x18\x03 \x02(\x02\x12\r\n\x05iotid\x18\x04 \x02(\t\x12\x13\n\x0biotselfLink\x18\x05 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x02(\t\x12\x16\n\x0ehistoricalLink\x18\x07 \x02(\t\x12\x12\n\nthingsLink\x18\x08 \x02(\t\"N\n\x14\x45xperiment2Locations\x12\x36\n\x0b\x65xperiment2\x18\x01 \x03(\x0b\x32!.Experiment2Data.Experiment2_prop'
)




_EXPERIMENT2_PROP = _descriptor.Descriptor(
  name='Experiment2_prop',
  full_name='Experiment2Data.Experiment2_prop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Experiment2Data.Experiment2_prop.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Experiment2Data.Experiment2_prop.latitude', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Experiment2Data.Experiment2_prop.longitude', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iotid', full_name='Experiment2Data.Experiment2_prop.iotid', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iotselfLink', full_name='Experiment2Data.Experiment2_prop.iotselfLink', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='Experiment2Data.Experiment2_prop.description', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='historicalLink', full_name='Experiment2Data.Experiment2_prop.historicalLink', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='thingsLink', full_name='Experiment2Data.Experiment2_prop.thingsLink', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=209,
)


_EXPERIMENT2LOCATIONS = _descriptor.Descriptor(
  name='Experiment2Locations',
  full_name='Experiment2Data.Experiment2Locations',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='experiment2', full_name='Experiment2Data.Experiment2Locations.experiment2', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=289,
)

_EXPERIMENT2LOCATIONS.fields_by_name['experiment2'].message_type = _EXPERIMENT2_PROP
DESCRIPTOR.message_types_by_name['Experiment2_prop'] = _EXPERIMENT2_PROP
DESCRIPTOR.message_types_by_name['Experiment2Locations'] = _EXPERIMENT2LOCATIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Experiment2_prop = _reflection.GeneratedProtocolMessageType('Experiment2_prop', (_message.Message,), {
  'DESCRIPTOR' : _EXPERIMENT2_PROP,
  '__module__' : 'experiment2_pb2'
  # @@protoc_insertion_point(class_scope:Experiment2Data.Experiment2_prop)
  })
_sym_db.RegisterMessage(Experiment2_prop)

Experiment2Locations = _reflection.GeneratedProtocolMessageType('Experiment2Locations', (_message.Message,), {
  'DESCRIPTOR' : _EXPERIMENT2LOCATIONS,
  '__module__' : 'experiment2_pb2'
  # @@protoc_insertion_point(class_scope:Experiment2Data.Experiment2Locations)
  })
_sym_db.RegisterMessage(Experiment2Locations)


# @@protoc_insertion_point(module_scope)
