# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: address.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='address.proto',
  package='AddressFI',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\raddress.proto\x12\tAddressFI\"\xa3\x01\n\x0c\x41\x64\x64ress_prop\x12\x17\n\x0f\x61\x64\x64rHousenumber\x18\x01 \x02(\t\x12\x12\n\naddrStreet\x18\x02 \x02(\t\x12\x10\n\x08\x61\x64\x64rCity\x18\x03 \x02(\t\x12\x0b\n\x03\x66id\x18\x04 \x02(\x05\x12\x0e\n\x06source\x18\x05 \x02(\t\x12\x10\n\x08\x61\x64\x64rUnit\x18\x06 \x02(\t\x12\x13\n\x0b\x66ullAddress\x18\x07 \x02(\t\x12\x10\n\x08geometry\x18\x08 \x02(\t\"3\n\x07\x41\x64\x64ress\x12(\n\x07\x61\x64\x64ress\x18\x01 \x03(\x0b\x32\x17.AddressFI.Address_prop'
)




_ADDRESS_PROP = _descriptor.Descriptor(
  name='Address_prop',
  full_name='AddressFI.Address_prop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='addrHousenumber', full_name='AddressFI.Address_prop.addrHousenumber', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='addrStreet', full_name='AddressFI.Address_prop.addrStreet', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='addrCity', full_name='AddressFI.Address_prop.addrCity', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fid', full_name='AddressFI.Address_prop.fid', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='AddressFI.Address_prop.source', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='addrUnit', full_name='AddressFI.Address_prop.addrUnit', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fullAddress', full_name='AddressFI.Address_prop.fullAddress', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='geometry', full_name='AddressFI.Address_prop.geometry', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=192,
)


_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='AddressFI.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='AddressFI.Address.address', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=245,
)

_ADDRESS.fields_by_name['address'].message_type = _ADDRESS_PROP
DESCRIPTOR.message_types_by_name['Address_prop'] = _ADDRESS_PROP
DESCRIPTOR.message_types_by_name['Address'] = _ADDRESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Address_prop = _reflection.GeneratedProtocolMessageType('Address_prop', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS_PROP,
  '__module__' : 'address_pb2'
  # @@protoc_insertion_point(class_scope:AddressFI.Address_prop)
  })
_sym_db.RegisterMessage(Address_prop)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'address_pb2'
  # @@protoc_insertion_point(class_scope:AddressFI.Address)
  })
_sym_db.RegisterMessage(Address)


# @@protoc_insertion_point(module_scope)
